# Generated by Django 3.0.4 on 2020-03-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_test_hub'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Test_hub',
            new_name='Test_hub_model',
        ),
    ]
