# Generated by Django 3.0.4 on 2020-03-09 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200309_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test_hub_model',
            name='Events',
        ),
    ]
