# Generated by Django 3.0.4 on 2020-03-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_test_hub_model_events'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='Eind_tijd',
            field=models.TimeField(default='23:59'),
        ),
        migrations.AddField(
            model_name='event',
            name='Start_tijd',
            field=models.TimeField(default='00:00'),
        ),
    ]
