# Generated by Django 3.0.4 on 2020-03-10 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200310_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Eind_tijd',
            new_name='eind_tijd',
        ),
        migrations.RemoveField(
            model_name='event',
            name='Start_tijd',
        ),
        migrations.AddField(
            model_name='event',
            name='start_tijd',
            field=models.TimeField(default='00:00'),
        ),
    ]
