# Generated by Django 3.0.4 on 2020-03-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20200310_0957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test_hub_model',
        ),
    ]
