# Generated by Django 3.0.4 on 2020-03-10 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_delete_test_hub_model'),
        ('events', '0002_auto_20200308_1547'),
    ]

    operations = [
    ]
