# Generated by Django 3.0.4 on 2020-04-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_merge_20200310_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='AI',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='Back_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='Cloud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='Front_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='Product_owner',
            field=models.BooleanField(default=False),
        ),
    ]
