# Generated by Django 3.0.4 on 2020-04-21 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testpage_1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='testpage1',
        ),
    ]
